import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { Resend } from 'resend';
import { env } from '$env/dynamic/private';

// Initialize Resend lazily to avoid build-time errors
let resend: Resend | null = null;

function getResend(): Resend {
  if (!resend) {
    const apiKey = env.RESEND_API_KEY;
    if (!apiKey) {
      throw new Error('RESEND_API_KEY environment variable is not set');
    }
    resend = new Resend(apiKey);
  }
  return resend;
}

export const POST: RequestHandler = async ({ request }) => {
  try {
    const { email, reportHtml, documentName, overallScore, riskLevel } = await request.json();

    if (!email || !reportHtml) {
      return json({ error: 'Missing required fields' }, { status: 400 });
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return json({ error: 'Invalid email address' }, { status: 400 });
    }

    const scoreColor = overallScore >= 70 ? '#27AE60' : overallScore >= 40 ? '#F39C12' : '#E74C3C';
    const riskColor = riskLevel?.toLowerCase().includes('low') ? '#27AE60' : 
                      riskLevel?.toLowerCase().includes('medium') ? '#F39C12' : '#E74C3C';

    const emailHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Your Greenwash Check Report</title>
      </head>
      <body style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #333; line-height: 1.6;">
        <div style="background: linear-gradient(135deg, #1a365d 0%, #2d4a3e 100%); padding: 30px; border-radius: 12px 12px 0 0; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 24px;">Greenwash Check</h1>
          <p style="color: #a0d8b3; margin: 10px 0 0;">Bill C-59 Compliance Assessment</p>
        </div>
        
        <div style="background: #f7fafc; padding: 30px; border: 1px solid #e2e8f0;">
          <h2 style="color: #2d3748; margin-top: 0;">Your Assessment Report is Ready</h2>
          
          <p>Thank you for using Greenwash Check. Your assessment for <strong>${documentName || 'your document'}</strong> has been completed.</p>
          
          <div style="background: white; border-left: 4px solid ${scoreColor}; padding: 20px; margin: 20px 0; border-radius: 4px;">
            <div style="display: flex; align-items: center; gap: 20px;">
              <div>
                <span style="font-size: 48px; font-weight: bold; color: ${scoreColor};">${overallScore}</span>
                <span style="color: #718096;">/100</span>
              </div>
              <div>
                <span style="display: inline-block; padding: 4px 12px; border-radius: 4px; color: white; background: ${riskColor}; font-weight: 500;">${riskLevel}</span>
              </div>
            </div>
          </div>
          
          <p style="color: #4a5568;">The full detailed report is attached below. It includes:</p>
          <ul style="color: #4a5568;">
            <li>Competition Bureau 6 Principles Assessment</li>
            <li>Detailed findings and evidence</li>
            <li>Specific recommendations for improvement</li>
            <li>Legal risk assessment</li>
          </ul>
          
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e2e8f0;">
            <p style="color: #718096; font-size: 14px;">
              <strong>Next Steps:</strong> Review the detailed findings below and prioritise addressing high-severity issues first. 
              Consider consulting with legal counsel for claims identified as high risk.
            </p>
          </div>
        </div>
        
        <div style="background: #1a365d; padding: 20px; border-radius: 0 0 12px 12px; text-align: center;">
          <p style="color: #a0d8b3; margin: 0; font-size: 14px;">
            Powered by <a href="https://greenwash-check.onrender.com" style="color: #27AE60; text-decoration: none;">Greenwash Check</a> | 
            A free tool by <a href="https://muuvment.com" style="color: #27AE60; text-decoration: none;">Muuvment Ltd.</a>
          </p>
        </div>
        
        <div style="margin-top: 30px; padding: 20px; background: #f7fafc; border-radius: 8px;">
          <h3 style="color: #2d3748; margin-top: 0;">Full Assessment Report</h3>
          ${reportHtml}
        </div>
        
        <div style="margin-top: 20px; padding: 15px; background: #fef3c7; border: 1px solid #fcd34d; border-radius: 8px; font-size: 12px; color: #92400e;">
          <strong>Disclaimer:</strong> This report is generated by an AI-powered assessment tool and provides informational analysis only. 
          It does not constitute legal or compliance advice. Muuvment Ltd. shall not be held liable for any damages arising from reliance on this assessment.
          This service is governed by the laws of the Province of Ontario, Canada.
        </div>
      </body>
      </html>
    `;

    const { data, error } = await getResend().emails.send({
      from: 'Greenwash Check <reports@greenwash-check.com>',
      to: [email],
      subject: `Your Greenwash Check Report - ${documentName || 'Assessment'} (Score: ${overallScore}/100)`,
      html: emailHtml,
    });

    if (error) {
      console.error('Resend error:', error);
      return json({ error: 'Failed to send email. Please try again.' }, { status: 500 });
    }

    console.log(`=== REPORT EMAIL SENT ===`);
    console.log(`To: ${email}`);
    console.log(`Document: ${documentName}`);
    console.log(`Score: ${overallScore}`);
    console.log(`Email ID: ${data?.id}`);
    console.log(`=========================`);

    return json({ success: true, emailId: data?.id });
  } catch (error) {
    console.error('Send report error:', error);
    return json({ error: 'Failed to send report email' }, { status: 500 });
  }
};
